### ISSUE TITLE
lint- Yamalı bohça

### ISSUE THREAD

**Issue by hqv** [aciksozluk/aciksozluk-api#11]
Şimdi [.eslintrc](https://github.com/aciksozluk/aciksozluk-api/blob/master/.eslintrc)'yi okudum da, 2 yahut 4 indent'e izin verilmesi kodun yamalı bohçaya dönmesine yol açabilir. En azından indentation için bir autoformat aygıtı gerek. Bana iki indentation da uyar- 4'e alışsam da vim'e js dosyaları için ayrı bir şey eklerim, ne olacak. 

Örneğin şu anda [bin/www](https://github.com/aciksozluk/aciksozluk-api/blob/master/bin/www) 2 indent iken [gulpfile](https://github.com/aciksozluk/aciksozluk-api/blob/master/gulpfile.js) 4 indent. Neden? Bana kalırsa development için ikisini birbirine çevirebilecek bir autoformat aygıtı olsun ama pre-commit hook'u ikisinden birine çevirsin, böylece codebase uniform olur.

PR açmadım çünkü gulp için filan autoformat aygıtı vardır diye düşündüm, ilk bulduğum şeyi koyup fazladan bloat eklemek istemedim.

**Comment by onur** [comment]
2 ve 4'e izin yok. Sadece 4. Bastaki 2 warning yerine error vermesini sagliyor.

bin/www gözden kacmis. Gulp sadece sonu js olan dosyalari kontrol ediyor. Kac gundur de review bekliyordum oysa ki :heart:

**Comment by hqv** [comment]
O zaman yanlış anlamışım, 4 indent. Kapatıyorum.
