### ISSUE TITLE
Depo adının "aciksozluk-api-server" olarak değiştirilmesi

### ISSUE THREAD

**Issue by onur** [aciksozluk/aciksozluk-api#14]
Bu uygulama'nın görevi programcılara bir javascript API'i sağlamaktan çok, HTTP üzerinden bir restful API sunmak. Bu nedenle bu deponun adının aciksozluk-api-server olarak değiştirilmesi çok daha mantıklı.

İleride bu API için yazılacak clientler, aciksozluk-api-client ya da aciksozluk-api-python etc. şeklinde oluşturulabilir.

**Comment by hmert** [comment]
madem bu açık bir sözlük, neden Telegram gibi server tarafının standartını yazıp daha sonrasında bir çok kişinin/grubun server tarafını yazmasına imkan sağlanmıyor?
http://jsonapi.org/

**Comment by onur** [comment]
@hmert bizim de zaten amacımız o. Şu an bu depoda geliştirilen uygulama bir JSON RESTful API sağlayacak ve isteyen istediği client'ı (web arayüz, phone app, bot vs.) geliştirebilecek.

**Comment by o** [comment]
@onur Huseyin, speclerin belirtilmesinden bahsediyor. Isteyen bu spexler latindan istedigi dilde implementasyon saglamali diyor. Senin anladigindan farkli.

**Comment by onur** [comment]
@o evet gönderdikten sonra anladım.

@hmert standart yapmaktan daha çok kullanıcı deneyiminin ön planda olduğu daha iyi bir sözlük yapmak için buradayız. Ama istersen bir standart çıkartarak katkıda bulunabilirsin. Sözlüğün özelliklerini şu başlıkta tartışıyoruz: aciksozluk/aciksozluk#23 Daha bir karara varabilmiş değiliz.

**Comment by hqv** [comment]
@hmert, link pek güzelmiş, orada linklenen [bikeshed.org](http://bikeshed.org/) da. aciksozluk/aciksozluk#2'yi gördüm adeta.

Adı değiştirebiliriz, bence OK.

**Comment by ramesaliyev** [comment]
İsim bence de değiştirilebilir, hatta değişmeli.

**Comment by onur** [comment]
Öyleyse değiştiriyorum.

**Comment by KiPSOFT** [comment]
bence http://jsonapi.org çok mantıklı bu işi geliştirmek için geç kalmış sayılmayız bir yandan da node server'ı geliştirmeye devam edebiliriz.
