### ISSUE TITLE
Bu repo api için midir?

### ISSUE THREAD

**Issue by ramesaliyev** [aciksozluk/aciksozluk-api#2]
Selamlar,

Bu repo api için açıldıysa adı api olmalı. Diğer reponun adını aciksozluk yapıp genel tartışmaları oradan çevirelim diye konuşmuştuk. aciksozluk monolitic bir app olmayacağından tek bir aciksozluk reposu altında kod yazmak doğru değil.

https://github.com/aciksozluk/altyapi-tartisma/issues/20

**Comment by hqv** [comment]
Adını aciksozluk-api diye değiştiriyorum.

**Comment by ramesaliyev** [comment]
@hqv Abi başına neden aciksozluk yazıyoruz ki? zaten aciksozluk organizasyonu altında.

**Comment by hqv** [comment]
Belki bu organizasyonun daha sonra başka türlü projeleri olabilir. Fazla verbosity zarar getirmez.

**Comment by ramesaliyev** [comment]
@hqv mantıklı dedin, kapatıyorum issue'yu.

**Comment by onur** [comment]
Tüm referans linklerimi öldürdüğünüz için teşekkürler.

**Comment by ramesaliyev** [comment]
@onur linkleri permalink olarak değil issue referansı olarak verirsen otomatik güncelleniyorlar.
